WIP: feat: React router migration
hawtio/hawtio-next pull request #84
Opened 2023-02-07 13:10 UTC by mmelko

This is a WIP PR. I've currently migrated and refactored all (I hope) routes in all plugins except camel.

Thinks to do: 
- migrate camel plugin,
- configure local dev environment to auto redirect to [host]/hawtio, this was removed in router v6
@tadayosi  please check if applicable so far

2023-02-08 05:12 UTC, tadayosi requested changes
there are minor comments but overall it looks great. thanks!

2023-02-08 05:12 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/JmxContent.tsx
> +              <Route key="root" path="/*" element={<Navigate to={"attributes"}/>}/>
with this path setting, when accessing http://localhost:3000/hawtio/?con=springboot from Connect it redirects to http://localhost:3000/hawtio/jmx/*?con=springboot (note `*`). Why can't it be `/`?

2023-02-08 05:12 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/index.ts
> +    path: 'jmx/*',
if react router v6 requires `/*` it shouldn't be configured here in each plugin. it should be a ui page concern so should be implemented in `HawtioPage.tsx`. A plugin shouldn't be aware of such impl details.

2023-02-08 05:12 UTC, tadayosi commented on packages/hawtio/src/preferences/HawtioPreferences.tsx
> +          <Route path='/' element ={<Navigate  to={'home'} />} />
`element =` -> `element=`

2023-02-08 05:12 UTC, tadayosi commented on packages/hawtio/src/ui/page/HawtioPage.tsx
> +              </Route>
why not use `/>`?

2023-02-08 05:24 UTC, tadayosi commented
> * configure local dev environment to auto redirect to [host]/hawtio, this was removed in router v6

Playing with this pull req, I don't see this issue is so severe to fix before merging the fix. It's just a dev env issue and developers can bookmark http://localhost:3000/hawtio/ instead of http://localhost:3000/ to workaround it.

What seems more important is a code formatting issue, since there have been a lot of changes regarding code formatting in this pull req. Which IDE / code formatter do you use?  VS Code and Prettier?  I feel that we've come to the point where we need to use the same code formatter, because if each person uses their own formatter I wouldn't like to see a lot of changes on just formatting every time in the future.

2023-02-08 08:33 UTC, mmelko commented on packages/hawtio/src/help/HawtioHelp.tsx
> +                    blabla
ooops ..

2023-02-08 12:58 UTC, mmelko commented
@tadayosi I fixed styling issues (I hope) and incorporated your comments, please check.

2023-02-08 14:40 UTC, tadayosi requested changes
overall it looks great but there are still a few unnecessary code changes.

2023-02-08 14:40 UTC, tadayosi commented on packages/hawtio/src/help/HawtioHelp.tsx
> +import {helpRegistry} from './registry'
unnecessary code change

2023-02-08 14:40 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/JmxContent.tsx
> +          <JmxContentMBeans/>
unnecessary code change

2023-02-08 14:40 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/JmxContent.tsx
> +  const {node, setNode} = useContext(MBeanTreeContext)
unnecessary code change

2023-02-08 14:40 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/JmxContent.tsx
> +            <InfoCircleIcon/> This node has no MBeans.
unnecessary code change

2023-02-08 14:40 UTC, tadayosi commented on packages/hawtio/src/plugins/jmx/JmxContent.tsx
> +        <TableBody onRowClick={selectChild}/>
unnecessary code change

2023-02-09 09:15 UTC, tadayosi approved these changes
LGTM now, thanks!

2023-02-09 09:15 UTC, tadayosi commented
@mmelko Once conflicts resolved, can we merge this one?

2023-02-09 09:49 UTC, merged